### PR TITLE
update justinrainbow/json-schema to 5.3.0

### PR DESCRIPTION
**Pull request by grnd-alt**

### CODE REVIEW

**Comment by juliusknorr** [comment]
Can you also prepare the server bump pr so we can run deck tests against those branches?

**Comment by grnd-alt** [comment]
https://github.com/nextcloud/server/pull/49285

**Comment by grnd-alt** [comment]
green deck CI tested here: https://github.com/nextcloud/deck/pull/6517

**Review by juliusknorr — APPROVED** [review]

**Comment by nickvergessen** [comment]
3rdparty PRs should only be merged when the server PR is approved and mergable.
Now there is red CI on server:
grafik

**Pull request merged**
