### PR TITLE
Add an adapter for HTTPlug and PSR7

### PR DESCRIPTION
**Pull request by ChristophWurst**
Ref http://httplug.io/

Once we have this (for 19), I will finish and publish a nextcloud-http-client meta package for apps, so composer can pull libraries that depend on an HTTP implementation, without actually pulling in an implementation (and thus avoiding the dependency hell).

Future package repo: https://github.com/ChristophWurst/nextcloud-http-client

### CODE REVIEW

**Comment by icewind1991** [comment]
nextcloud-http-client would provide some glue code to call the nc system http client?

**Comment by ChristophWurst** [comment]
> nextcloud-http-client would provide some glue code to call the nc system http client?

No, it will just say that it's provided. No code required. The guzzle adapter pulled in here will be found and used as implementation.

It actually works already. Just installed `sentry/sentry` instead of `sentry/sdk` in https://github.com/ChristophWurst/nextcloud_sentry and it removes the guzzle 6.5 packages (that causes an issue with the 6.3 here) and added the package. With `master` of this repo I get an exception because no HTTP implementation is found. As soon as I switch to this PR's branch it finds the Guzzle adapter and uses that.

**Comment by ChristophWurst** [comment]
So it actually goes to Guzzle directly and has nothing to do with the HTTP client abstraction in Nextcloud.

**Comment by ChristophWurst** [comment]
https://github.com/ChristophWurst/nextcloud_sentry/pull/169/files#diff-1da2c7edc898c70e5a79a9997c98cecc <- see the lockfile updates. No more Guzzle in the app :)

**Pull request merged**
