### PR TITLE
adding daita/nc-small-php-tools

### PR DESCRIPTION
**Pull request by daita**

### CODE REVIEW

**Comment by MorrisJobke** [comment]
For what do you need this?

**Comment by MorrisJobke** [comment]
I guess for https://github.com/nextcloud/server/issues/13478? Mind to open a PR in server as well?

**Comment by daita** [comment]
I need it for this PR: https://github.com/nextcloud/server/pull/15357

**Comment by daita** [comment]
However, not sure we need to rush-push it for NC17

**Comment by MorrisJobke** [comment]
Thanks for the link 👍

**Comment by ChristophWurst** [comment]
obsolete, I guess

**Pull request closed without merging**
