### PR TITLE
Add composer install check

### PR DESCRIPTION
**Pull request by skjnldsv**
Signed-off-by: John Molakvoæ (skjnldsv) <skjnldsv@protonmail.com>

### CODE REVIEW

**Comment by skjnldsv** [comment]
Hum, why is it failing? :(

**Comment by skjnldsv** [comment]
@ChristophWurst do you know why my `composer i` inlude tests?
Is there something special I need to run?

**Comment by rullzer** [comment]
Because the packages have them
they should be fixed. Hence we just kill them ourselves here... but also we don't ship the tests..

**Comment by ChristophWurst** [comment]
> @ChristophWurst do you know why my `composer i` inlude tests?
> Is there something special I need to run?

Yep, it's the packages that ship tests.

**Comment by skjnldsv** [comment]
so let's close this ?

**Comment by ChristophWurst** [comment]
Can't we

* `composer install`
* (git magic that removes all ignored files)
* `composer dump-autoload`
* (git check for uncommitted changes)

**Comment by skjnldsv** [comment]
>  Command "dump-autoloader" is not defined.

**Comment by ChristophWurst** [comment]
No idea why the action gets a different diff. Could someone try the steps locally?

**Comment by skjnldsv** [comment]
> No idea why the action gets a different diff. Could someone try the steps locally?

works  for me.

Maybe a composer version issue?

**Comment by skjnldsv** [comment]
:tada:

**Pull request merged**
