### PR TITLE
Enforce to install with --no-dev

### PR DESCRIPTION
**Pull request by nickvergessen**
Signed-off-by: Joas Schilling <coding@schilljs.com>

### CODE REVIEW

**Review by blizzz — APPROVED** [review]

**Comment by blizzz** [comment]
mh, shouldn't it fail?

**Comment by blizzz** [comment]
https://github.com/nextcloud/3rdparty/blob/60b4baae842dc480b7a1b46bafccb7b9c85777ad/.github/workflows/composer.yml#L32

**Comment by blizzz** [comment]
run it before those steps?

**Comment by nickvergessen** [comment]
yeah, already figured :P

**Comment by nickvergessen** [comment]
tada  🎉

**Pull request merged**
