### PR TITLE
Bump/symfony

### PR DESCRIPTION
**Pull request by rullzer**

### CODE REVIEW

**Comment by icewind1991** [comment]
I would prefer to keep the version requirements specific (without `~`)

**Comment by rullzer** [comment]
@icewind1991 the idea here would be that we could tell tools (like dependabot) to notify us when there are new releases that fit our requirements.

Like for symfony we want to stay on 3.4 (LTS). That way we won't miss updates (or security updates).

People will use this repo as a submodule to their php anyway.

**Comment by ChristophWurst** [comment]
> @icewind1991 the idea here would be that we could tell tools (like dependabot) to notify us when there are new releases that fit our requirements.

This should be possible now: https://dependabot.com/blog/updating-older-versions

**Comment by MorrisJobke** [comment]
conflicts :/

**Comment by rullzer** [comment]
Will take care!

**Comment by rullzer** [comment]
Rebased!

**Pull request merged**
