### PR TITLE
Repairing BASE64 encoded vCard version 3

### PR DESCRIPTION
**Pull request by Webbeh**
Fix https://github.com/nextcloud/server/issues/3366

Simple re-application of the same patch as upstream
https://github.com/sabre-io/vobject/pull/441

### CODE REVIEW

**Comment by skjnldsv** [comment]
Hum, this would require also a repair step in nextcloud/server, right?

**Comment by Webbeh** [comment]
@evert on the upstream issue (https://github.com/sabre-io/vobject/pull/415) commented that sabre/dav calls the validate function with the repair flag by default. There shouldn't be any more step needed in nextcloud, assuming that repair flag wasn't removed.

**Comment by Webbeh** [comment]
After "blindly" applying the patch to Nextcloud's Property.php, it seems to work flawlessy with my device, which seems to imply that the "repair" option is called by nextcloud by default as well -> nothing more to do than patch.

**Comment by MorrisJobke** [comment]
@rullzer @skjnldsv @ChristophWurst @georgehrke 🏓

**Comment by Webbeh** [comment]
I will try beta 16 and report back here.

**Comment by MorrisJobke** [comment]
> @rullzer @skjnldsv @ChristophWurst @georgehrke 🏓

🏓

**Comment by Webbeh** [comment]
Thanks!

**Comment by skjnldsv** [comment]
Drone is not enabled here @MorrisJobke ?

**Comment by MorrisJobke** [comment]
> Drone is not enabled here @MorrisJobke ?

Correct, because 3rdparty without an update to the server code is quite meaningless. Thus a PR to server is needed to check against our code base.

**Comment by skjnldsv** [comment]
Ideally we could get https://github.com/icewind1991/SearchDAV/issues/9
And then we'd be able to upgrade sbre/dav to 4.2.0+ where this fix is

https://github.com/sabre-io/vobject/releases/tag/4.2.0

**Comment by icewind1991** [comment]
> Ideally we could get icewind1991/SearchDAV#9

done

**Comment by skjnldsv** [comment]
@icewind1991 you used 4.0.x, we would need 4.2.x :see_no_evil: :heart:

**Comment by Webbeh** [comment]
@skjnldsv #398 contains the fix, so this will be able to be closed.
image

**Comment by icewind1991** [comment]
> @icewind1991 you used 4.0.x, we would need 4.2.x see_no_evil heart

sabre/dav only goes up to 4.0, it's sabre/vobject is 4.2

**Comment by skjnldsv** [comment]
Ah sorry!! All good then!

**Pull request closed without merging**
