### PR TITLE
Speedup classmap loading

### PR DESCRIPTION
**Pull request by rullzer**
Since composer 1.1.0 (see
https://github.com/composer/composer/blob/master/CHANGELOG.md) There is
support for a static ClassMap. This reduces the load time on php >= 5.6
to almost nothing.

CC: @LukasReschke @MorrisJobke @nickvergessen @icewind1991

### CODE REVIEW

**Comment by icewind1991** [comment]
Do we have unit tests running on old php versions for this?

**Comment by rullzer** [comment]
Good question... @MorrisJobke do we?

**Comment by MorrisJobke** [comment]
> Good question... @MorrisJobke do we?

Not yet. @rullzer and I are working on this.

**Comment by rullzer** [comment]
@icewind1991 we do now... See https://github.com/nextcloud/server/issues/320

**Comment by icewind1991** [comment]
:+1:

**Pull request merged**
