### PR TITLE
Bump christophwurst/id3parser to 0.1.4

### PR DESCRIPTION
**Pull request by come-nc**
Signed-off-by: Côme Chilliet <come.chilliet@nextcloud.com>

Needed for PHP 8.1 compatibility

Replaces https://github.com/nextcloud/3rdparty/pull/935

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]

**Review by st3iny — APPROVED** [review]

**Comment by pachulo** [comment]
Hi! Could this be backported to `stable22` and `stable21`?
Thanks!

**Comment by ChristophWurst** [comment]
What would be the benefits of the backport?

**Comment by pachulo** [comment]
Without the backport https://github.com/nextcloud/previewgenerator throws errors when used with PHP 8.x, which is supported by nextcloud 21 & 22.

More info: https://github.com/nextcloud/previewgenerator/issues/249

**Comment by pachulo** [comment]
so, how can this be done @ChristophWurst ?

**Pull request merged**
