### PR TITLE
Add SabreDav Patch for iTip Broker

### PR DESCRIPTION
**Pull request by SebastianKrupinski**

### CODE REVIEW

**Comment by SebastianKrupinski** [comment]
> Is there an associated upstream PR for this? If so, please link it here :)

Yes.

Sabre: https://github.com/sabre-io/dav/pull/1559

And there are several issues at the moment we are can not fix because we can overwrite the broker. You want me to list some of them?

**Comment by ChristophWurst** [comment]
Please open a server PR with this 3rdparty checkout. This is needed for a full CI run.

**Comment by SebastianKrupinski** [comment]
> Please open a server PR with this 3rdparty checkout. This is needed for a full CI run.

Done. https://github.com/nextcloud/server/pull/47998

**Review by st3iny — APPROVED** [review]
Clean

**Review by NameNoQuality — APPROVED** [review]

**Pull request merged**
