### PR TITLE
Fix infinite propfinds reporting files as directories

### PR DESCRIPTION
**Pull request by nickvergessen**
Early port of https://github.com/fruux/sabre-dav/pull/982/files which also has a unit test showing the issue.
Fix https://github.com/nextcloud/server/issues/5543

Would be nice if this is also backported to 12 🤷‍

### CODE REVIEW

**Comment by MorrisJobke** [comment]
backport in #57

**Comment by MorrisJobke** [comment]
Please update the submodule via a server PR - same for the backport.

**Comment by jaapio** [comment]
Is it possible to backport this to v11 as well?

**Comment by nickvergessen** [comment]
Our current information is that 11 would not suffer from this error?!

**Pull request merged**
