### PR TITLE
Add TLSv1_2 Support (from upstream swiftmailer) server issue #11408

### PR DESCRIPTION
**Pull request by mgoppold**

### CODE REVIEW

**Comment by MorrisJobke** [comment]
@mgoppold Is this from an upstream pull request? Because we try to have as little as possible patches ontop of our dependencies. If not please try to hand this in to the maintainers at https://github.com/swiftmailer/swiftmailer as well. So both projects can benefit from this improvement. 👍 

Thanks for the contribution nevertheless.

**Comment by mgoppold** [comment]
> @mgoppold Is this from an upstream pull request? Because we try to have as little as possible patches ontop of our dependencies. If not please try to hand this in to the maintainers at https://github.com/swiftmailer/swiftmailer as well. So both projects can benefit from this improvement. 
> 
> Thanks for the contribution nevertheless.

Yes, these Lines are from Upstream and solve the issue with TLSv1.2. I see the full update of swiftmailer is in the queue but if you want to fix this issue for older releases too, that should also fit.

**Comment by ChristophWurst** [comment]
@mgoppold thanks for this fix :v: 

I think we should look into integrating https://github.com/nextcloud/3rdparty/pull/155 instead. Without looking into the details, it's a minor update and if they follow semver we should be able to update from 6.0 to 6.1 easily. Any objections, @MorrisJobke @rullzer?

**Comment by MorrisJobke** [comment]
> I think we should look into integrating #155 instead. Without looking into the details, it's a minor update and if they follow semver we should be able to update from 6.0 to 6.1 easily. Any objections, @MorrisJobke @rullzer?

Go ahead 👍

**Comment by ChristophWurst** [comment]
> Go ahead +1

Went ahead: https://github.com/nextcloud/3rdparty/pull/155. Not sure if I know how to update libs in this repo though :man_shrugging:

**Comment by mgoppold** [comment]
The swiftmailer-6.1.3 works fine for me:

```
pushd SERVERROOT/nextcloud/3rdparty/swiftmailer
mv swiftmailer/ swiftmailer.nc
wget https://github.com/swiftmailer/swiftmailer/archive/v6.1.3.zip
unzip  v6.1.3.zip
ln -s swiftmailer-6.1.3 swiftmailer
chown -R wwwrun: swiftmailer*

```

And Test 

- Basic setting -> Email server -> send mail  &#10004;
- Share by E-Mail  &#10004;
- Add Attendee to Calendar  &#10004;

all with no Warnings / Errors in my Logs (apache-Server-logs).

**Comment by MorrisJobke** [comment]
Thanks - we merged it in #155 and will ship it in the next major release of Nextcloud.

**Pull request closed without merging**
