### PR TITLE
Fix phpdocs

### PR DESCRIPTION
**Pull request by LukasReschke**
Required for https://github.com/nextcloud/server/pull/5776

### CODE REVIEW

**Comment by rullzer** [comment]
maybe also send pr upstream?

**Comment by MorrisJobke** [comment]
> maybe also send pr upstream?

The PRs are linked 🙈

**Comment by rullzer** [comment]
@MorrisJobke to sabre et al I mean :P

**Comment by MorrisJobke** [comment]
> @MorrisJobke to sabre et al I mean :P

I know:

https://github.com/fruux/sabre-xml/pull/128
https://github.com/rackspace/php-opencloud/pull/711

**Pull request merged**
