### PR TITLE
Bump deepdiver/zipstreamer from 1.1.1 to 2.0.0

### LINKED ISSUE #482: Update deepdiver/zipstreamer to v2.0.0
v2.0.0 is available, currently v1.1.1 is vendored.

### PR DESCRIPTION
**Pull request by LorbusChris**
Closes #482

### CODE REVIEW

**Comment by ChristophWurst** [comment]
Adjusted slightly with latest composer to hopefully make CI pass

**Review by ChristophWurst — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]

**Review by ChristophWurst — CHANGES_REQUESTED** [review]
drops all the doctrine and other important stuff

**Review by ChristophWurst — APPROVED** [review]
Rebased

**Review by ihsanali01 — COMMENTED** [review]
Thanks

**Pull request merged**
