### PR TITLE
Update Sabre/dav to 3.2.1

### PR DESCRIPTION
**Pull request by daniellandau**
Sabre/dav has released a new patch release, this pull request updates to that. The new version is needed for improving the startup performance of the Contacts app: https://github.com/nextcloud/contacts/issues/12.

This is an updated version of https://github.com/nextcloud/3rdparty/pull/30.

### CODE REVIEW

**Comment by rullzer** [comment]
Please also open a PR in the server for the upgraded 3rdparty ;)

**Comment by daniellandau** [comment]
I'd need to have the hash of the merge commit from this repository before that, or am I misunderstanding something? Or are you going to fast forward master to this commit?

**Comment by phsc** [comment]
Please also note, that there is already sabre/dav 3.2.2. This fixes a problem with CardDAV in 3.2.1, which could also be relevant for Nextcloud.

**Comment by rullzer** [comment]
Aaaah also you did not bump using composer. Ok let me create a PR and we switch to 3.2.2 directly.

**Pull request closed without merging**
