### PR TITLE
Bump symfony/event-dispatcher to 5.4

### PR DESCRIPTION
**Pull request by vitormattos**
I god error when I run `occ upgrade` after I did pull on server to get newest source from master branch. I have one app with `symfony/event-dispatcher` on `composer.lock` using newest version of this package and I identified a problem of argument typing because the method [GenericEvent->getArgument()](https://github.com/symfony/event-dispatcher/blob/5.4/GenericEvent.php#L60) on version >= 5 of `symfony/event-dispatcher` have typed argument forcing to string and the [GenericEventWrapper->getArgument()](https://github.com/nextcloud/server/blob/master/lib/private/EventDispatcher/GenericEventWrapper.php#L91) haven't typed argument.

Suggested steps to solve the problem:
- [x] bump the package symfony/event-dispatcher on 3rdparty
- [ ] bump the 3rdparty submodule on server
- [ ] Fix all unit tests on server after bump `3rdparty` submodule
- [ ] Implement typed argument on `GenericEventWrapper` on server
- [ ] Change the places on server that request `GenericEventWrapper->getArgument` and cast the argument from int to string

What I did on this PR?
```
composer require -W symfony/console symfony/event-dispatcher-contracts symfony/event-dispatcher
```

### CODE REVIEW

**Comment by vitormattos** [comment]
I did `rebase` with CI fix and I think that I haven't permission to force push:

```
To github.com:nextcloud/3rdparty.git
 ! [rejected]          bump-symfony_event-dispatcher -> bump-symfony_event-dispatcher (stale info)
error: failed to push some refs to 'github.com:nextcloud/3rdparty.git'
```

**Comment by ChristophWurst** [comment]
is it ok to mix symfony 4 and symfony 5 components?

**Comment by vitormattos** [comment]
I only bumped the symfony/event-dispatcher and his dependencies.

I can try to check the impact on `server` as a part of this review and report here.

**Comment by vitormattos** [comment]
outdated.

**Pull request closed without merging**
