### PR TITLE
Bump PHP to 8.0

### PR DESCRIPTION
**Pull request by come-nc**
Drop 7.4 on master

Signed-off-by: Côme Chilliet <come.chilliet@nextcloud.com>

### CODE REVIEW

**Review by nickvergessen — APPROVED** [review]

**Comment by come-nc** [comment]
Rebased

**Comment by come-nc** [comment]
Rebased

**Review by ChristophWurst — CHANGES_REQUESTED** [review]
Changes in `php-opencloud/openstack` are unrelated

**Comment by nickvergessen** [comment]
That happened because most numbers are "fixed" with `^X.Y` instead of `^X.Y.Z` which means it also installs any `X.(Y+1)` so it updated 3.1.z to 3.2.a because that now works as 8.0 is the minimum....

**Comment by ChristophWurst** [comment]
if you change composer.json and run `composer update php` no other deps should be touched

**Comment by come-nc** [comment]
> if you change composer.json and run `composer update php` no other deps should be touched

This is what I did.

**Review by ChristophWurst — APPROVED** [review]
:elephant: then

**Comment by come-nc** [comment]
> elephant then

Actually I remembered wrong, I did what you said and had:
```
> composer update php --no-dev
Gathering patches from patch file.
No patches supplied.
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - php-opencloud/openstack is locked to version v3.1.0 and an update of this package was not requested.
    - php-opencloud/openstack v3.1.0 requires php ^7.2.5 -> your php version (8.0; overridden via config.platform, actual: 8.1.2) does not satisfy that requirement.
```

Which is why I also updated this lib.

**Comment by come-nc** [comment]
Rebuilt on top of master

**Pull request merged**
