### PR TITLE
Build sabre-uri uris with HTTP password

### PR DESCRIPTION
**Pull request by tcitworld**
Related to https://github.com/nextcloud/calendar/issues/70

### CODE REVIEW

**Comment by MorrisJobke** [comment]
See the comment by evert. :/

**Comment by rugk** [comment]
You mean [this](https://github.com/sabre-io/uri/pull/33#issuecomment-418446996) as I assume. However, why not merge this anyway? His main reason for the comment is that the lib is deprecated and he thus won't merge it. You may still merge it here…

**Comment by rugk** [comment]
https://github.com/sabre-io/uri/pull/33#issuecomment-418446996 has been closed (aka rejected), so what is the way forward to fix https://github.com/nextcloud/calendar/issues/70 now?

**Comment by MorrisJobke** [comment]
> [sabre-io/uri#33 (comment)](https://github.com/sabre-io/uri/pull/33#issuecomment-418446996) has been closed (aka rejected), so what is the way forward to fix [nextcloud/calendar#70](https://github.com/nextcloud/calendar/issues/70) now?

Hard to say - @rullzer any idea how to move forward here. I tend to not patch too much, but maybe this one is fine.

**Comment by ChristophWurst** [comment]
I'd also say we get this in upstream or in the worst case have our own fork. But patching the vendored files is asking for trouble IMO

**Pull request closed without merging**
