### PR TITLE
Issue 1280 - Google and some other client does not recognize invitation updates

### PR DESCRIPTION
**Pull request by alexander-ivannikov**
Implementation of a fix for https://github.com/nextcloud/calendar/issues/1280

### CODE REVIEW

**Comment by MorrisJobke** [comment]
cc @tcitworld @georgehrke

**Comment by MorrisJobke** [comment]
@alexander-ivannikov Thanks for this fix. Did you create a pull request against the upstream project that we are using here? You can find it here: https://github.com/sabre-io/vobject/

We try to keep patches to libraries to a bare minimum and aim to provide fixes to the upstream project so that others can benefit from it as well.

**Comment by alexander-ivannikov** [comment]
@MorrisJobke Yes, please find it here https://github.com/sabre-io/vobject/pull/463

**Comment by MorrisJobke** [comment]
> @MorrisJobke Yes, please find it here [sabre-io/vobject#463](https://github.com/sabre-io/vobject/pull/463)

Awesome - thank you!

**Comment by vimmerru** [comment]
@MorrisJobke 

The fix was merged to main Sabre codebase. See https://github.com/sabre-io/vobject/pull/463 What we should do to get this fixed in Nextcloud?

**Comment by MorrisJobke** [comment]
Apply this as a patch of the linked PR to this repo and list this patch inside https://github.com/nextcloud/3rdparty/blob/master/patches.txt.

Then once a version with this fix is released we will update to it.

**Comment by georgehrke** [comment]
@rullzer It would be really great to get this in for Nc 17.

**Comment by kesselb** [comment]
Thanks @alexander-ivannikov :+1: 

In the meantime sabre was updated and your fix landed :tada:

**Pull request closed without merging**
