### PR TITLE
Try to support 7.3 for DAV

### PR DESCRIPTION
**Pull request by nickvergessen**
Copied some patches from all the sabre repos.

Alternatively we can upgrade to 4.0.0-alpha*

This should then fix the tests of the activity app:
https://github.com/nextcloud/activity/pull/318#pullrequestreview-177884175

### CODE REVIEW

**Comment by MorrisJobke** [comment]
@nickvergessen @rullzer What to do? Patch or upgrade to an alpha?

**Comment by nickvergessen** [comment]
I would go with the patch for now and also would like to backport it to 15, because the spam is quite annoying.

For 16 we can then also upgrade to the alpha and help moving that forward

**Pull request merged**
