### PR TITLE
Bump doctrine/dbal to 2.7.2

### PR DESCRIPTION
**Pull request by rullzer**
Signed-off-by: Roeland Jago Douma <roeland@famdouma.nl>

### CODE REVIEW

**Comment by MorrisJobke** [comment]
What about https://github.com/nextcloud/3rdparty/pull/187 ?

**Comment by rullzer** [comment]
> What about #187 ?

Good question... @nickvergessen is that still needed?

**Comment by nickvergessen** [comment]
Yes still required as upstream didnt merge it yet:
https://github.com/doctrine/dbal/pull/3104

**Comment by rullzer** [comment]
Ok I'll take care this evening.

**Pull request merged**
