### PR TITLE
Support for property filters in addressbook-query

### PR DESCRIPTION
**Pull request by daniellandau**
This is the patch for 3.2 from https://github.com/fruux/sabre-dav/issues/889 excluding tests

This is related to improving the startup performance of the Contacts app: https://github.com/nextcloud/contacts/issues/12.

### CODE REVIEW

**Comment by eppfel** [comment]
@nextcloud/contacts

**Comment by MorrisJobke** [comment]
Usually we don't apply patches but use upstream patch releases. 

If this is not possible we should add a note to https://github.com/nextcloud/3rdparty/blob/master/patches.txt about this patch.

cc @LukasReschke @rullzer

**Comment by daniellandau** [comment]
There didn't seem to be a release of sabre/dav with this patch.

**Comment by skjnldsv** [comment]
Yep, maybe should we wait for official sabre dav release?

**Comment by skjnldsv** [comment]
In fact; maybe we shouldn't.
Since this has been merged and backported into sabre/dav master, we can assume the enxt release will be shipped with this patch.

I said, LGTM! :)

**Comment by rullzer** [comment]
No please just wait for sabre to release a new version! We should keep the amount of patching to a minimum. The earliest this will be in is NC12. So no need to rush.

**Comment by skjnldsv** [comment]
ok! ! 👍

**Comment by daniellandau** [comment]
@rullzer this is now just an update to Sabre/dav 3.2.1.

**Comment by eppfel** [comment]
Hey @daniellandau , nice meeting you at FOSDEM. I think if you close this and make a fresh PR for the update, everything will be cleaner and the chances of the others reviewing it quick are higher 😁

**Comment by daniellandau** [comment]
It was nice meeting you too @eppfel! I'm closing this now in favor of the new pull request.

**Pull request closed without merging**
