### PR TITLE
Add giggsey/libphonenumber-for-php

### PR DESCRIPTION
**Pull request by nickvergessen**
Signed-off-by: Joas Schilling <coding@schilljs.com>

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]

**Comment by MorrisJobke** [comment]
Conflicts :/

**Comment by nickvergessen** [comment]
Solved

**Comment by MorrisJobke** [comment]
Composer.lock is conflicting again :/

**Comment by nickvergessen** [comment]
Yeah, because you merged #470

**Pull request merged**
